host= db.wywstpvyjcmsqzzsausr.supabase.co
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db.wywstpvyjcmsqzzsausr.supabase.co:5432/postgres?user=postgres&password=DnLi150225*!
spring.datasource.username=postgres
spring.datasource.password=DnLi150225*!

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update