spring.application.name=Backend_api

spring.application.name=sistema-api
server.port=8081

spring.datasource.url=${jdbc:postgresql://db.wywstpvyjcmsqzzsausr.supabase.co:5432/postgres?user=postgres&password=[DnLi150225*!]}
spring.datasource.username=${postgres}
spring.datasource.password=${DnLi150225*!}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true